#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MassText.Resource", IsApplication=true)]

namespace MassText
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int themeColor = 2130771972;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int magnify = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int clearCacheButton = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int composeMessageSendBUtton = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int contactList = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int contactListSearch = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int contactSelectionList = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int dateInput = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int dateInputHeader = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int delayBetweenTypeSpinner = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int delayTimeInput = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int delayTypeSpinner = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int deleteButton = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int discardMessageButton = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int fileName = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int filterSpinner = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int forceSendPendingButton = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int importContactFromDeviceButton = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int importExcelFromDeviceButton = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int importProgressBar = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int logsList = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int messageBetweenDelay = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int messageField = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int messagePreview = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int messageSchedulerForm = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int proceedButton = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int repeatCheckBox = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int resendFailedBUtton = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int scheduleMessageButton = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int selectAllButton = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int sendNowButton = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int setScheduleButton = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int statusOfMessageBundle = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int timeOfDayInput = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int timeOfDayInputHeader = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int viewLogsButton = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int viewMessagesList = 2130903074;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040001
			public const int activity_main = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int compose_message = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int contact_picker = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int layout1 = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int loading = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int logs = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int send_message = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int view_messages = 2130968584;
			
			// aapt resource value: 0x7F040000
			public const int XMLFile1 = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_foreground = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_round = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int action_settings = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_name = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
